name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "AIDoc/**"


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}